### ISSUE TITLE
More Bot templates

### ISSUE THREAD

**Issue by timoniq** [vkbottle/vkbottle#69]
### Idea
Make some bot templates to make bots easily created "in one string" like this:
```python
Echo("token").ready().run(skip_updates=False)
```
From [echo template](https://github.com/timoniq/vkbottle/blob/master/examples/tests/templates/echo_bot.py) example

### Todo
Some template ideas to make in the nearest future:

- [x] `Echo` bot template
- [ ] `ChatManager` bot template
- [x] `TextBot` bot template  

Leave your enhancements for bot templates in this issue. Pull requests are welcome
